/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { BACKUP_TYPE } from './models/BACKUP_TYPE';
export type { BaseCreateNetworkBody } from './models/BaseCreateNetworkBody';
export type { BOND_MODE } from './models/BOND_MODE';
export type { Branded_host_ } from './models/Branded_host_';
export type { Branded_PIF_ } from './models/Branded_PIF_';
export type { Branded_task_ } from './models/Branded_task_';
export type { Branded_VDI_ } from './models/Branded_VDI_';
export type { CreateActionReturnType__id_string__ } from './models/CreateActionReturnType__id_string__';
export type { CreateActionReturnType__id_Unbrand_XoNetwork__91_id_93___ } from './models/CreateActionReturnType__id_Unbrand_XoNetwork__91_id_93___';
export type { CreateActionReturnType__id_Unbrand_XoVdi__91_id_93___ } from './models/CreateActionReturnType__id_Unbrand_XoVdi__91_id_93___';
export type { CreateActionReturnType__id_Unbrand_XoVm__91_id_93___ } from './models/CreateActionReturnType__id_Unbrand_XoVm__91_id_93___';
export type { CreateActionReturnType__id_XenApiVm_at_uuid__ } from './models/CreateActionReturnType__id_XenApiVm_at_uuid__';
export type { CreateActionReturnType_void_ } from './models/CreateActionReturnType_void_';
export type { CreateInternalNetworkBody } from './models/CreateInternalNetworkBody';
export type { CreateVdiBody } from './models/CreateVdiBody';
export type { CreateVifBody } from './models/CreateVifBody';
export type { DashboardBackupRepositoriesSizeInfo } from './models/DashboardBackupRepositoriesSizeInfo';
export type { DashboardBackupsInfo } from './models/DashboardBackupsInfo';
export type { DOMAIN_TYPE } from './models/DOMAIN_TYPE';
export type { Exclude_SUPPORTED_VDI_FORMAT_qcow2_ } from './models/Exclude_SUPPORTED_VDI_FORMAT_qcow2_';
export type { HasNoAuthorization } from './models/HasNoAuthorization';
export type { HOST_POWER_STATE } from './models/HOST_POWER_STATE';
export type { InsertableXoServer } from './models/InsertableXoServer';
export type { IP_CONFIGURATION_MODE } from './models/IP_CONFIGURATION_MODE';
export type { IPV6_CONFIGURATION_MODE } from './models/IPV6_CONFIGURATION_MODE';
export type { IsEmptyData } from './models/IsEmptyData';
export type { IsMaybeExpired_DashboardBackupRepositoriesSizeInfo_ } from './models/IsMaybeExpired_DashboardBackupRepositoriesSizeInfo_';
export type { IsMaybeExpired_DashboardBackupsInfo_ } from './models/IsMaybeExpired_DashboardBackupsInfo_';
export type { IsMaybeExpired_IsEmptyData_ } from './models/IsMaybeExpired_IsEmptyData_';
export type { McpStatus } from './models/McpStatus';
export type { MissingPatchesInfo } from './models/MissingPatchesInfo';
export type { NdjsonStream } from './models/NdjsonStream';
export type { Omit_CreateVdiParams_91_0_93__SR_or_other_config_ } from './models/Omit_CreateVdiParams_91_0_93__SR_or_other_config_';
export type { Omit_CreateVifParams_91_0_93__network_or_VM_or_other_config_or_qos_algorithm_params_ } from './models/Omit_CreateVifParams_91_0_93__network_or_VM_or_other_config_or_qos_algorithm_params_';
export type { Omit_Unbrand_Parameters_Xapi_91_VBD_create_93___91_0_93___VM_or_VDI_ } from './models/Omit_Unbrand_Parameters_Xapi_91_VBD_create_93___91_0_93___VM_or_VDI_';
export type { Omit_Unbrand_VmDashboard_at_quickInfo__creation_ } from './models/Omit_Unbrand_VmDashboard_at_quickInfo__creation_';
export type { Partial_Record_VM_OPERATIONS_boolean_or_string_or_null__ } from './models/Partial_Record_VM_OPERATIONS_boolean_or_string_or_null__';
export type { Partial_Unbrand_AnyPrivilege__ } from './models/Partial_Unbrand_AnyPrivilege__';
export type { Partial_Unbrand_XoAclRole__ } from './models/Partial_Unbrand_XoAclRole__';
export type { Partial_Unbrand_XoAlarm__ } from './models/Partial_Unbrand_XoAlarm__';
export type { Partial_Unbrand_XoBackupLog__ } from './models/Partial_Unbrand_XoBackupLog__';
export type { Partial_Unbrand_XoBackupRepository__ } from './models/Partial_Unbrand_XoBackupRepository__';
export type { Partial_Unbrand_XoGroup__ } from './models/Partial_Unbrand_XoGroup__';
export type { Partial_Unbrand_XoHost__ } from './models/Partial_Unbrand_XoHost__';
export type { Partial_Unbrand_XoMessage__ } from './models/Partial_Unbrand_XoMessage__';
export type { Partial_Unbrand_XoNetwork__ } from './models/Partial_Unbrand_XoNetwork__';
export type { Partial_Unbrand_XoPbd__ } from './models/Partial_Unbrand_XoPbd__';
export type { Partial_Unbrand_XoPci__ } from './models/Partial_Unbrand_XoPci__';
export type { Partial_Unbrand_XoPgpu__ } from './models/Partial_Unbrand_XoPgpu__';
export type { Partial_Unbrand_XoPool__ } from './models/Partial_Unbrand_XoPool__';
export type { Partial_Unbrand_XoProxy__ } from './models/Partial_Unbrand_XoProxy__';
export type { Partial_Unbrand_XoRestoreLog__ } from './models/Partial_Unbrand_XoRestoreLog__';
export type { Partial_Unbrand_XoSchedule__ } from './models/Partial_Unbrand_XoSchedule__';
export type { Partial_Unbrand_XoServer__ } from './models/Partial_Unbrand_XoServer__';
export type { Partial_Unbrand_XoSm__ } from './models/Partial_Unbrand_XoSm__';
export type { Partial_Unbrand_XoSr__ } from './models/Partial_Unbrand_XoSr__';
export type { Partial_Unbrand_XoTask__ } from './models/Partial_Unbrand_XoTask__';
export type { Partial_Unbrand_XoUser__ } from './models/Partial_Unbrand_XoUser__';
export type { Partial_Unbrand_XoVbd__ } from './models/Partial_Unbrand_XoVbd__';
export type { Partial_Unbrand_XoVdi__ } from './models/Partial_Unbrand_XoVdi__';
export type { Partial_Unbrand_XoVdiSnapshot__ } from './models/Partial_Unbrand_XoVdiSnapshot__';
export type { Partial_Unbrand_XoVm__ } from './models/Partial_Unbrand_XoVm__';
export type { Partial_Unbrand_XoVmBackupArchive__ } from './models/Partial_Unbrand_XoVmBackupArchive__';
export type { Partial_Unbrand_XoVmController__ } from './models/Partial_Unbrand_XoVmController__';
export type { Partial_Unbrand_XoVmSnapshot__ } from './models/Partial_Unbrand_XoVmSnapshot__';
export type { Partial_Unbrand_XoVmTemplate__ } from './models/Partial_Unbrand_XoVmTemplate__';
export type { Partial_UnbrandAnyXoBackupJob_ } from './models/Partial_UnbrandAnyXoBackupJob_';
export type { Partial_UnbrandedXoAlarm_ } from './models/Partial_UnbrandedXoAlarm_';
export type { Partial_UnbrandedXoMessage_ } from './models/Partial_UnbrandedXoMessage_';
export type { Partial_UnbrandedXoPif_ } from './models/Partial_UnbrandedXoPif_';
export type { Partial_UnbrandedXoVif_ } from './models/Partial_UnbrandedXoVif_';
export type { Partial_UnbrandXoMetadataBackupJob_ } from './models/Partial_UnbrandXoMetadataBackupJob_';
export type { Partial_UnbrandXoMirrorBackupJob_ } from './models/Partial_UnbrandXoMirrorBackupJob_';
export type { Partial_UnbrandXoVmBackupJob_ } from './models/Partial_UnbrandXoVmBackupJob_';
export type { PGPU_DOM0_ACCESS } from './models/PGPU_DOM0_ACCESS';
export type { Pick_CreateVdiParams_91_0_93__Exclude_keyofCreateVdiParams_91_0_93__SR_or_other_config__ } from './models/Pick_CreateVdiParams_91_0_93__Exclude_keyofCreateVdiParams_91_0_93__SR_or_other_config__';
export type { Pick_CreateVifParams_91_0_93__Exclude_keyofCreateVifParams_91_0_93__network_or_VM_or_other_config_or_qos_algorithm_params__ } from './models/Pick_CreateVifParams_91_0_93__Exclude_keyofCreateVifParams_91_0_93__network_or_VM_or_other_config_or_qos_algorithm_params__';
export type { Pick_Unbrand_Parameters_Xapi_91_VBD_create_93___91_0_93___Exclude_keyofUnbrand_Parameters_Xapi_91_VBD_create_93___91_0_93___VM_or_VDI__ } from './models/Pick_Unbrand_Parameters_Xapi_91_VBD_create_93___91_0_93___Exclude_keyofUnbrand_Parameters_Xapi_91_VBD_create_93___91_0_93___VM_or_VDI__';
export type { Pick_Unbrand_VmDashboard_at_quickInfo__Exclude_keyofUnbrand_VmDashboard_at_quickInfo__creation__ } from './models/Pick_Unbrand_VmDashboard_at_quickInfo__Exclude_keyofUnbrand_VmDashboard_at_quickInfo__creation__';
export type { PingResponse } from './models/PingResponse';
export type { PoolDashboard } from './models/PoolDashboard';
export type { PRIMARY_ADDRESS_TYPE } from './models/PRIMARY_ADDRESS_TYPE';
export type { PromiseWriteInStreamError } from './models/PromiseWriteInStreamError';
export type { Record_string__timestamp_number__ } from './models/Record_string__timestamp_number__';
export type { Record_string_attaching_ } from './models/Record_string_attaching_';
export type { Record_string_HOST_ALLOWED_OPERATIONS_ } from './models/Record_string_HOST_ALLOWED_OPERATIONS_';
export type { Record_string_number_ } from './models/Record_string_number_';
export type { Record_string_POOL_ALLOWED_OPERATIONS_ } from './models/Record_string_POOL_ALLOWED_OPERATIONS_';
export type { Record_string_StatValues_ } from './models/Record_string_StatValues_';
export type { Record_string_STORAGE_OPERATIONS_ } from './models/Record_string_STORAGE_OPERATIONS_';
export type { Record_string_string_ } from './models/Record_string_string_';
export type { Record_string_string_or_null_ } from './models/Record_string_string_or_null_';
export type { Record_string_unknown_ } from './models/Record_string_unknown_';
export type { Record_string_VDI_OPERATIONS_ } from './models/Record_string_VDI_OPERATIONS_';
export type { Record_string_VM_OPERATIONS_ } from './models/Record_string_VM_OPERATIONS_';
export type { Record_VM_OPERATIONS_string_ } from './models/Record_VM_OPERATIONS_string_';
export type { Record_XoHost_at_id_XapiHostStats_or__error_Record_string_unknown___ } from './models/Record_XoHost_at_id_XapiHostStats_or__error_Record_string_unknown___';
export type { RecordStatValues } from './models/RecordStatValues';
export type { SendObjects_Partial_Unbrand_AnyPrivilege___ } from './models/SendObjects_Partial_Unbrand_AnyPrivilege___';
export type { SendObjects_Partial_Unbrand_XoAclRole___ } from './models/SendObjects_Partial_Unbrand_XoAclRole___';
export type { SendObjects_Partial_Unbrand_XoAlarm___ } from './models/SendObjects_Partial_Unbrand_XoAlarm___';
export type { SendObjects_Partial_Unbrand_XoBackupLog___ } from './models/SendObjects_Partial_Unbrand_XoBackupLog___';
export type { SendObjects_Partial_Unbrand_XoBackupRepository___ } from './models/SendObjects_Partial_Unbrand_XoBackupRepository___';
export type { SendObjects_Partial_Unbrand_XoGroup___ } from './models/SendObjects_Partial_Unbrand_XoGroup___';
export type { SendObjects_Partial_Unbrand_XoHost___ } from './models/SendObjects_Partial_Unbrand_XoHost___';
export type { SendObjects_Partial_Unbrand_XoMessage___ } from './models/SendObjects_Partial_Unbrand_XoMessage___';
export type { SendObjects_Partial_Unbrand_XoNetwork___ } from './models/SendObjects_Partial_Unbrand_XoNetwork___';
export type { SendObjects_Partial_Unbrand_XoPbd___ } from './models/SendObjects_Partial_Unbrand_XoPbd___';
export type { SendObjects_Partial_Unbrand_XoPci___ } from './models/SendObjects_Partial_Unbrand_XoPci___';
export type { SendObjects_Partial_Unbrand_XoPgpu___ } from './models/SendObjects_Partial_Unbrand_XoPgpu___';
export type { SendObjects_Partial_Unbrand_XoPool___ } from './models/SendObjects_Partial_Unbrand_XoPool___';
export type { SendObjects_Partial_Unbrand_XoProxy___ } from './models/SendObjects_Partial_Unbrand_XoProxy___';
export type { SendObjects_Partial_Unbrand_XoRestoreLog___ } from './models/SendObjects_Partial_Unbrand_XoRestoreLog___';
export type { SendObjects_Partial_Unbrand_XoSchedule___ } from './models/SendObjects_Partial_Unbrand_XoSchedule___';
export type { SendObjects_Partial_Unbrand_XoServer___ } from './models/SendObjects_Partial_Unbrand_XoServer___';
export type { SendObjects_Partial_Unbrand_XoSm___ } from './models/SendObjects_Partial_Unbrand_XoSm___';
export type { SendObjects_Partial_Unbrand_XoSr___ } from './models/SendObjects_Partial_Unbrand_XoSr___';
export type { SendObjects_Partial_Unbrand_XoTask___ } from './models/SendObjects_Partial_Unbrand_XoTask___';
export type { SendObjects_Partial_Unbrand_XoUser___ } from './models/SendObjects_Partial_Unbrand_XoUser___';
export type { SendObjects_Partial_Unbrand_XoVbd___ } from './models/SendObjects_Partial_Unbrand_XoVbd___';
export type { SendObjects_Partial_Unbrand_XoVdi___ } from './models/SendObjects_Partial_Unbrand_XoVdi___';
export type { SendObjects_Partial_Unbrand_XoVdiSnapshot___ } from './models/SendObjects_Partial_Unbrand_XoVdiSnapshot___';
export type { SendObjects_Partial_Unbrand_XoVm___ } from './models/SendObjects_Partial_Unbrand_XoVm___';
export type { SendObjects_Partial_Unbrand_XoVmBackupArchive___ } from './models/SendObjects_Partial_Unbrand_XoVmBackupArchive___';
export type { SendObjects_Partial_Unbrand_XoVmController___ } from './models/SendObjects_Partial_Unbrand_XoVmController___';
export type { SendObjects_Partial_Unbrand_XoVmSnapshot___ } from './models/SendObjects_Partial_Unbrand_XoVmSnapshot___';
export type { SendObjects_Partial_Unbrand_XoVmTemplate___ } from './models/SendObjects_Partial_Unbrand_XoVmTemplate___';
export type { SendObjects_Partial_UnbrandAnyXoBackupJob__ } from './models/SendObjects_Partial_UnbrandAnyXoBackupJob__';
export type { SendObjects_Partial_UnbrandedXoAlarm__ } from './models/SendObjects_Partial_UnbrandedXoAlarm__';
export type { SendObjects_Partial_UnbrandedXoMessage__ } from './models/SendObjects_Partial_UnbrandedXoMessage__';
export type { SendObjects_Partial_UnbrandedXoPif__ } from './models/SendObjects_Partial_UnbrandedXoPif__';
export type { SendObjects_Partial_UnbrandedXoVif__ } from './models/SendObjects_Partial_UnbrandedXoVif__';
export type { SendObjects_Partial_UnbrandXoMetadataBackupJob__ } from './models/SendObjects_Partial_UnbrandXoMetadataBackupJob__';
export type { SendObjects_Partial_UnbrandXoMirrorBackupJob__ } from './models/SendObjects_Partial_UnbrandXoMirrorBackupJob__';
export type { SendObjects_Partial_UnbrandXoVmBackupJob__ } from './models/SendObjects_Partial_UnbrandXoVmBackupJob__';
export type { SrSizeInfo } from './models/SrSizeInfo';
export type { StatValues } from './models/StatValues';
export type { Unbrand_AnyPrivilege_ } from './models/Unbrand_AnyPrivilege_';
export type { Unbrand_CreateBondedNetworkBody_ } from './models/Unbrand_CreateBondedNetworkBody_';
export type { Unbrand_CreateNetworkBody_ } from './models/Unbrand_CreateNetworkBody_';
export type { Unbrand_CreateVmBody_ } from './models/Unbrand_CreateVmBody_';
export type { Unbrand_SafeOmit_AnyPrivilege_id__ } from './models/Unbrand_SafeOmit_AnyPrivilege_id__';
export type { Unbrand_SafeOmit_Partial_AnyPrivilege__id_or_roleId__ } from './models/Unbrand_SafeOmit_Partial_AnyPrivilege__id_or_roleId__';
export type { Unbrand_UnbrandedXoMetadataBackupJob_ } from './models/Unbrand_UnbrandedXoMetadataBackupJob_';
export type { Unbrand_UnbrandedXoMirrorBackupJob_ } from './models/Unbrand_UnbrandedXoMirrorBackupJob_';
export type { Unbrand_UnbrandedXoVmBackupJob_ } from './models/Unbrand_UnbrandedXoVmBackupJob_';
export type { Unbrand_VmDashboard_at_backupsInfo_91_replication_93__ } from './models/Unbrand_VmDashboard_at_backupsInfo_91_replication_93__';
export type { Unbrand_VmDashboard_at_quickInfo_91_creation_93__ } from './models/Unbrand_VmDashboard_at_quickInfo_91_creation_93__';
export type { Unbrand_VmDashboardBackupArchive_ } from './models/Unbrand_VmDashboardBackupArchive_';
export type { Unbrand_VmDashboardRun_ } from './models/Unbrand_VmDashboardRun_';
export type { Unbrand_XoAclRole_ } from './models/Unbrand_XoAclRole_';
export type { Unbrand_XoAlarm_ } from './models/Unbrand_XoAlarm_';
export type { Unbrand_XoAuthenticationToken_ } from './models/Unbrand_XoAuthenticationToken_';
export type { Unbrand_XoBackupLog_ } from './models/Unbrand_XoBackupLog_';
export type { Unbrand_XoBackupRepository_ } from './models/Unbrand_XoBackupRepository_';
export type { Unbrand_XoGroup_ } from './models/Unbrand_XoGroup_';
export type { Unbrand_XoHost_ } from './models/Unbrand_XoHost_';
export type { Unbrand_XoMessage_ } from './models/Unbrand_XoMessage_';
export type { Unbrand_XoMirrorBackupScheduleSettings_ } from './models/Unbrand_XoMirrorBackupScheduleSettings_';
export type { Unbrand_XoNetwork_ } from './models/Unbrand_XoNetwork_';
export type { Unbrand_XoPbd_ } from './models/Unbrand_XoPbd_';
export type { Unbrand_XoPci_ } from './models/Unbrand_XoPci_';
export type { Unbrand_XoPgpu_ } from './models/Unbrand_XoPgpu_';
export type { Unbrand_XoPif_ } from './models/Unbrand_XoPif_';
export type { Unbrand_XoPool_ } from './models/Unbrand_XoPool_';
export type { Unbrand_XoProxy_ } from './models/Unbrand_XoProxy_';
export type { Unbrand_XoRestoreLog_ } from './models/Unbrand_XoRestoreLog_';
export type { Unbrand_XoSchedule_ } from './models/Unbrand_XoSchedule_';
export type { Unbrand_XoServer_ } from './models/Unbrand_XoServer_';
export type { Unbrand_XoSm_ } from './models/Unbrand_XoSm_';
export type { Unbrand_XoSr_ } from './models/Unbrand_XoSr_';
export type { Unbrand_XoTask_ } from './models/Unbrand_XoTask_';
export type { Unbrand_XoUser_ } from './models/Unbrand_XoUser_';
export type { Unbrand_XoVbd_ } from './models/Unbrand_XoVbd_';
export type { Unbrand_XoVdi_ } from './models/Unbrand_XoVdi_';
export type { Unbrand_XoVdiSnapshot_ } from './models/Unbrand_XoVdiSnapshot_';
export type { Unbrand_XoVif_ } from './models/Unbrand_XoVif_';
export type { Unbrand_XoVm_ } from './models/Unbrand_XoVm_';
export type { Unbrand_XoVmBackupArchive_ } from './models/Unbrand_XoVmBackupArchive_';
export type { Unbrand_XoVmBackupJobScheduleSettings_ } from './models/Unbrand_XoVmBackupJobScheduleSettings_';
export type { Unbrand_XoVmController_ } from './models/Unbrand_XoVmController_';
export type { Unbrand_XoVmSnapshot_ } from './models/Unbrand_XoVmSnapshot_';
export type { Unbrand_XoVmTemplate_ } from './models/Unbrand_XoVmTemplate_';
export type { UnbrandAnyXoBackupJob } from './models/UnbrandAnyXoBackupJob';
export type { UnbrandedVmDashboard } from './models/UnbrandedVmDashboard';
export type { UnbrandedXoAlarm } from './models/UnbrandedXoAlarm';
export type { UnbrandedXoMessage } from './models/UnbrandedXoMessage';
export type { UnbrandedXoPif } from './models/UnbrandedXoPif';
export type { UnbrandedXoVif } from './models/UnbrandedXoVif';
export type { UnbrandXoMetadataBackupJob } from './models/UnbrandXoMetadataBackupJob';
export type { UnbrandXoMirrorBackupJob } from './models/UnbrandXoMirrorBackupJob';
export type { UnbrandXoVmBackupJob } from './models/UnbrandXoVmBackupJob';
export type { UpdateGroupRequestBody } from './models/UpdateGroupRequestBody';
export type { UpdateUserRequestBody } from './models/UpdateUserRequestBody';
export type { UpdateVmRequestBody } from './models/UpdateVmRequestBody';
export type { VBD_MODE } from './models/VBD_MODE';
export type { VBD_TYPE } from './models/VBD_TYPE';
export type { VDI_TYPE } from './models/VDI_TYPE';
export type { VIF_LOCKING_MODE } from './models/VIF_LOCKING_MODE';
export type { VM_POWER_STATE } from './models/VM_POWER_STATE';
export type { WithHref_Partial_Unbrand_AnyPrivilege___ } from './models/WithHref_Partial_Unbrand_AnyPrivilege___';
export type { WithHref_Partial_Unbrand_XoAclRole___ } from './models/WithHref_Partial_Unbrand_XoAclRole___';
export type { WithHref_Partial_Unbrand_XoAlarm___ } from './models/WithHref_Partial_Unbrand_XoAlarm___';
export type { WithHref_Partial_Unbrand_XoBackupLog___ } from './models/WithHref_Partial_Unbrand_XoBackupLog___';
export type { WithHref_Partial_Unbrand_XoBackupRepository___ } from './models/WithHref_Partial_Unbrand_XoBackupRepository___';
export type { WithHref_Partial_Unbrand_XoGroup___ } from './models/WithHref_Partial_Unbrand_XoGroup___';
export type { WithHref_Partial_Unbrand_XoHost___ } from './models/WithHref_Partial_Unbrand_XoHost___';
export type { WithHref_Partial_Unbrand_XoMessage___ } from './models/WithHref_Partial_Unbrand_XoMessage___';
export type { WithHref_Partial_Unbrand_XoNetwork___ } from './models/WithHref_Partial_Unbrand_XoNetwork___';
export type { WithHref_Partial_Unbrand_XoPbd___ } from './models/WithHref_Partial_Unbrand_XoPbd___';
export type { WithHref_Partial_Unbrand_XoPci___ } from './models/WithHref_Partial_Unbrand_XoPci___';
export type { WithHref_Partial_Unbrand_XoPgpu___ } from './models/WithHref_Partial_Unbrand_XoPgpu___';
export type { WithHref_Partial_Unbrand_XoPool___ } from './models/WithHref_Partial_Unbrand_XoPool___';
export type { WithHref_Partial_Unbrand_XoProxy___ } from './models/WithHref_Partial_Unbrand_XoProxy___';
export type { WithHref_Partial_Unbrand_XoRestoreLog___ } from './models/WithHref_Partial_Unbrand_XoRestoreLog___';
export type { WithHref_Partial_Unbrand_XoSchedule___ } from './models/WithHref_Partial_Unbrand_XoSchedule___';
export type { WithHref_Partial_Unbrand_XoServer___ } from './models/WithHref_Partial_Unbrand_XoServer___';
export type { WithHref_Partial_Unbrand_XoSm___ } from './models/WithHref_Partial_Unbrand_XoSm___';
export type { WithHref_Partial_Unbrand_XoSr___ } from './models/WithHref_Partial_Unbrand_XoSr___';
export type { WithHref_Partial_Unbrand_XoTask___ } from './models/WithHref_Partial_Unbrand_XoTask___';
export type { WithHref_Partial_Unbrand_XoUser___ } from './models/WithHref_Partial_Unbrand_XoUser___';
export type { WithHref_Partial_Unbrand_XoVbd___ } from './models/WithHref_Partial_Unbrand_XoVbd___';
export type { WithHref_Partial_Unbrand_XoVdi___ } from './models/WithHref_Partial_Unbrand_XoVdi___';
export type { WithHref_Partial_Unbrand_XoVdiSnapshot___ } from './models/WithHref_Partial_Unbrand_XoVdiSnapshot___';
export type { WithHref_Partial_Unbrand_XoVm___ } from './models/WithHref_Partial_Unbrand_XoVm___';
export type { WithHref_Partial_Unbrand_XoVmBackupArchive___ } from './models/WithHref_Partial_Unbrand_XoVmBackupArchive___';
export type { WithHref_Partial_Unbrand_XoVmController___ } from './models/WithHref_Partial_Unbrand_XoVmController___';
export type { WithHref_Partial_Unbrand_XoVmSnapshot___ } from './models/WithHref_Partial_Unbrand_XoVmSnapshot___';
export type { WithHref_Partial_Unbrand_XoVmTemplate___ } from './models/WithHref_Partial_Unbrand_XoVmTemplate___';
export type { WithHref_Partial_UnbrandAnyXoBackupJob__ } from './models/WithHref_Partial_UnbrandAnyXoBackupJob__';
export type { WithHref_Partial_UnbrandedXoAlarm__ } from './models/WithHref_Partial_UnbrandedXoAlarm__';
export type { WithHref_Partial_UnbrandedXoMessage__ } from './models/WithHref_Partial_UnbrandedXoMessage__';
export type { WithHref_Partial_UnbrandedXoPif__ } from './models/WithHref_Partial_UnbrandedXoPif__';
export type { WithHref_Partial_UnbrandedXoVif__ } from './models/WithHref_Partial_UnbrandedXoVif__';
export type { WithHref_Partial_UnbrandXoMetadataBackupJob__ } from './models/WithHref_Partial_UnbrandXoMetadataBackupJob__';
export type { WithHref_Partial_UnbrandXoMirrorBackupJob__ } from './models/WithHref_Partial_UnbrandXoMirrorBackupJob__';
export type { WithHref_Partial_UnbrandXoVmBackupJob__ } from './models/WithHref_Partial_UnbrandXoVmBackupJob__';
export type { XapiHostStats } from './models/XapiHostStats';
export type { XapiHostStatsRaw } from './models/XapiHostStatsRaw';
export type { XapiPoolStats } from './models/XapiPoolStats';
export type { XapiStatsGranularity } from './models/XapiStatsGranularity';
export type { XapiStatsResponse_XapiHostStatsRaw_ } from './models/XapiStatsResponse_XapiHostStatsRaw_';
export type { XapiStatsResponse_XapiVmStatsRaw_ } from './models/XapiStatsResponse_XapiVmStatsRaw_';
export type { XapiVmStats } from './models/XapiVmStats';
export type { XapiVmStatsRaw } from './models/XapiVmStatsRaw';
export type { XcpPatches } from './models/XcpPatches';
export type { XoaDashboard } from './models/XoaDashboard';
export type { XoBackupJobGeneralSettings } from './models/XoBackupJobGeneralSettings';
export type { XoGuiRoutes } from './models/XoGuiRoutes';
export type { XoListenerType } from './models/XoListenerType';
export type { XoMetadataBackupJobScheduleSettings } from './models/XoMetadataBackupJobScheduleSettings';
export type { XoMirrorBackupGeneralSettings } from './models/XoMirrorBackupGeneralSettings';
export type { XoTask } from './models/XoTask';
export type { XoVmBackupJobGeneralSettings } from './models/XoVmBackupJobGeneralSettings';
export type { XsPatches } from './models/XsPatches';

export { AlarmsService } from './services/AlarmsService';
export { BackupArchivesService } from './services/BackupArchivesService';
export { BackupJobsService } from './services/BackupJobsService';
export { BackupLogsService } from './services/BackupLogsService';
export { BackupRepositoriesService } from './services/BackupRepositoriesService';
export { DocsService } from './services/DocsService';
export { EventsService } from './services/EventsService';
export { GroupsService } from './services/GroupsService';
export { HostsService } from './services/HostsService';
export { McpService } from './services/McpService';
export { MessagesService } from './services/MessagesService';
export { NetworksService } from './services/NetworksService';
export { PbdsService } from './services/PbdsService';
export { PcisService } from './services/PcisService';
export { PgpusService } from './services/PgpusService';
export { PifsService } from './services/PifsService';
export { PoolsService } from './services/PoolsService';
export { ProxiesService } from './services/ProxiesService';
export { RbacsService } from './services/RbacsService';
export { RestoreLogsService } from './services/RestoreLogsService';
export { SchedulesService } from './services/SchedulesService';
export { ServersService } from './services/ServersService';
export { SmsService } from './services/SmsService';
export { SrsService } from './services/SrsService';
export { TasksService } from './services/TasksService';
export { UsersService } from './services/UsersService';
export { VbdsService } from './services/VbdsService';
export { VdisService } from './services/VdisService';
export { VifsService } from './services/VifsService';
export { VmsService } from './services/VmsService';
export { XoaService } from './services/XoaService';
