import type { XoVm, XoHost } from './types'
import { v4 as uuid } from 'uuid'
export { uuid }

export function createMockVm(id: string, name?: string): XoVm {
  return {
    id: id as XoVm['id'],
    name_label: name ?? `VM ${id.slice(0, 8)}`,
    power_state: 'Halted' as XoVm['power_state'],
    type: 'VM' as XoVm['type'],
    VBDs: [],
    VIFs: [],
    $pool: '' as XoVm['$pool'],
    // $poolId: '' as XoVm['$poolId'],
    _xapiRef: '',
    uuid: id,
    $VBDs: [],
    $VGPUs: [],
    $container: '' as XoVm['$container'],
    CPUs: { max: 1, number: 1 },
    VGPUs: [],
    VTPMs: [],
    addresses: {},
    auto_poweron: false,
    bios_strings: {},
    blockedOperations: {} as XoVm['blockedOperations'],
    boot: {},
    creation: {},
    current_operations: {},
    expNestedHvm: false,
    isNestedVirtEnabled: false,
    hasVendorDevice: false,
    high_availability: '',
    isFirmwareSupported: true,
    memory: { dynamic: [], size: 0, static: [] },
    name_description: '',
    needsVtpm: false,
    os_version: null,
    other: {},
    secureBoot: false,
    snapshots: [],
    startDelay: 0,
    tags: [],
    viridian: false,
    virtualizationMode: 'hvm' as XoVm['virtualizationMode'],
    xenStoreData: {},
    vulnerabilities: { xsa468: false },
  } as unknown as XoVm
}

export function createMockHost(id: string, name?: string): XoHost {
  return {
    id: id as XoHost['id'],
    name_label: name ?? `Host ${id.slice(0, 8)}`,
    power_state: 'Running' as XoHost['power_state'],
    type: 'host' as XoHost['type'],
    $pool: '' as XoHost['$pool'],
    // $poolId: '' as XoHost['$poolId'],
    _xapiRef: '',
    uuid: id,
    $PBDs: [],
    $PCIs: [],
    $PGPUs: [],
    $PIFs: [],
    PCIs: [],
    PGPUs: [],
    PIFs: [],
    CPUs: {},
    cpus: {},
    address: '192.168.1.100',
    agentStartTime: null,
    bios_strings: {},
    build: '',
    chipset_info: {},
    current_operations: {},
    enabled: true,
    hostname: `host-${id.slice(0, 8)}.example.com`,
    hvmCapable: true,
    iscsiIqn: '',
    license_expiry: null,
    license_params: {},
    license_server: {},
    logging: {},
    memory: { size: 0, usage: 0 },
    multipathing: false,
    name_description: '',
    otherConfig: {},
    patches: [],
    powerOnMode: '',
    productBrand: '',
    rebootRequired: false,
    residentVms: [],
    startTime: null,
    supplementalPacks: [],
    tags: [],
    version: '',
    zstdSupported: true,
  } as unknown as XoHost
}
